// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBridgeApi.DAO;

namespace ShopBridgeApi.Migrations
{
    [DbContext(typeof(ShopBridgeContext))]
    partial class ShopBridgeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopBridge.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "N95 Mask",
                            Name = "N95",
                            Price = 100.0,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "PPE Kit",
                            Name = "PPE Kit",
                            Price = 5000.0,
                            Quantity = 3500
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Himalaya Sanitizer",
                            Name = "Himalaya Sanitizer",
                            Price = 150.0,
                            Quantity = 5000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
